name: Playwright Java Tests

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "17"
          cache: "maven"

      - name: Install Playwright browsers
        run: mvn exec:java -e -Dexec.mainClass=com.microsoft.playwright.CLI -Dexec.args="install --with-deps"

      - name: Cache Playwright browsers
        uses: actions/cache@v4
        with:
          path: ~/.cache/ms-playwright
          key: ${{ runner.os }}-playwright

      - name: Run UI tests (prod)
        run: mvn test -Dsurefire.printSummary=true -Denv=prod -Dtest=*UiTest
        env:
          CI: true
        continue-on-error: true

      - name: Run API tests (prod)
        run: mvn test -Dsurefire.printSummary=true -Denv=prod -Dtest=*ApiTest
        env:
          CI: true
        continue-on-error: true

      - name: Upload test results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: test-results
          path: |
            target/surefire-reports
            playwright-report
            traces
          retention-days: 7
          if-no-files-found: ignore